name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup enviroment
        run: |
          echo ${{ secrets.FIREBASE_API_KEY }} >> .env
          echo ${{ secrets.FIREBASE_AUTH_DOMAIN }} >> .env
          echo ${{ secrets.FIREBASE_PROJECT_ID }} >> .env
          echo ${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
          echo ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} >> .env
          echo ${{ secrets.FIREBASE_APP_ID }} >> .env
          echo ${{ secrets.FIREBASE_MEASUREMENT_ID }} >> .env

      - name: install package
        run: |
          yarn install --frozen-lockfile

      - name: generate Nuxt.js
        run: |
          yarn generate

      - name: deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
